#Usar nos servidores de Cloud
apiVersion: v1
kind: Service
metadata:
  name: svc-leandro-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: leandro-springboot