apiVersion: v1
kind: Pod
metadata:
  name: pod-leandro-springboot
  labels:
    app: leandro-springboot
spec:
  containers:
    - name: container-leandro-springboot
      image: leandrofabriciosarmento/springboot:1.2
      ports:
        - containerPort: 8080