apiVersion: v1
kind: Pod
metadata:
  name: pod-leandro-springboot
  labels:
    app: leandro-springboot
spec:
  containers:
    - name: container-leandro-springboot
      image: leandrofabriciosarmento/springboot:1.0
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: configmap-leandro
    - name: container-leandro-postgres
      image: postgres:14.5
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: configmap-leandro